spring:
  profiles:
    active: dev
  thymeleaf:
    check-template-location: false

---
spring:
  devtools:
    restart:
      enabled: true
  config:
    activate:
      on-profile: dev
greeting:
  message: "Hello from Dev environment!"

---
spring:
  config:
    activate:
      on-profile: prod
greeting:
  message: "Hello from Prod environment!"
